from tkinter import *
ventana=Tk()
ventana.geometry("300x300")
Widget_uno=Frame()
Widget_uno.grid(row=0,column=0)
Widget_uno.config(width=50,height=50)
etiqueta=Label(ventana,text= "NOMBRES Y APELLIDOS: ")
etiqueta.grid(row=1,column=0)
cuadro_texto=Entry()
cuadro_texto.grid(row=1,column=1)

Widget_dos=Frame()
Widget_dos.grid(row=2,column=0)
Widget_dos.config(width=50,height=50)
etiqueta=Label(ventana,text= "DNI: ")
etiqueta.grid(row=2,column=0)
cuadro_texto=Entry()
cuadro_texto.grid(row=2,column=1)

Widget_tres=Frame()
Widget_tres.grid(row=3,column=0)
Widget_tres.config(width=50,height=50)
etiqueta=Label(ventana,text= "CELULAR: ")
etiqueta.grid(row=3,column=0)
cuadro_texto=Entry()
cuadro_texto.grid(row=3,column=1)

Widget_cuatro=Frame()
Widget_cuatro.grid(row=4,column=0, columnspan=2)
Widget_cuatro.config(width=280,height=180)
Widget_cuatro.config(bg="black")
ventana.mainloop()
